// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebDataToJsonExtractor.Model.MobilePhone;
//
//    var gsmArenaModel = GsmArenaModel.FromJson(jsonString);

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Clerk.Processes.WebExtractorToJson.Model.GSMArena
{
    public partial class GsmArenaModel
    {
        [JsonProperty("Name")]
        public Name Name { get; set; }

        [JsonProperty("Network")]
        public Network Network { get; set; }

        [JsonProperty("Launch")]
        public Launch Launch { get; set; }

        [JsonProperty("Body")]
        public Body Body { get; set; }

        [JsonProperty("Display")]
        public Display Display { get; set; }

        [JsonProperty("Platform")]
        public Platform Platform { get; set; }

        [JsonProperty("Memory")]
        public Memory Memory { get; set; }

        [JsonProperty("Main Camera")]
        public MainCamera MainCamera { get; set; }

        [JsonProperty("Selfie camera")]
        public SelfieCamera SelfieCamera { get; set; }

        [JsonProperty("Sound")]
        public Sound Sound { get; set; }

        [JsonProperty("Comms")]
        public Comms Comms { get; set; }

        [JsonProperty("Features")]
        public Features Features { get; set; }

        [JsonProperty("Battery")]
        public Battery Battery { get; set; }

        [JsonProperty("Misc")]
        public Misc Misc { get; set; }

        [JsonProperty("Tests")]
        public Tests Tests { get; set; }
    }

    public partial class Battery
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Charging")]
        public List<string> Charging { get; set; }
    }

    public partial class Body
    {
        [JsonProperty("Dimensions")]
        public List<string> Dimensions { get; set; }

        [JsonProperty("Weight")]
        public List<string> Weight { get; set; }

        [JsonProperty("Build")]
        public List<string> Build { get; set; }

        [JsonProperty("SIM")]
        public List<string> Sim { get; set; }

        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }
    }

    public partial class Comms
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("WLAN")]
        public List<string> Wlan { get; set; }

        [JsonProperty("Bluetooth")]
        public List<string> Bluetooth { get; set; }

        [JsonProperty("GPS")]
        public List<string> Gps { get; set; }

        [JsonProperty("NFC")]
        public List<string> Nfc { get; set; }

        [JsonProperty("Radio")]
        public List<string> Radio { get; set; }

        [JsonProperty("USB")]
        public List<string> Usb { get; set; }
    }

    public partial class Display
    {
        [JsonProperty("Type")]
        public List<string> Type { get; set; }

        [JsonProperty("Size")]
        public List<string> Size { get; set; }

        [JsonProperty("Resolution")]
        public List<string> Resolution { get; set; }

        [JsonProperty("Protection")]
        public List<string> Protection { get; set; }

        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }
    }

    public partial class Features
    {
        [JsonProperty("Sensors")]
        public List<string> Sensors { get; set; }

        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }
    }

    public partial class Launch
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Announced")]
        public List<string> Announced { get; set; }

        [JsonProperty("Status")]
        public List<string> Status { get; set; }
    }

    public partial class MainCamera
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Triple")]
        public List<string> Triple { get; set; }

        [JsonProperty("Features")]
        public List<string> Features { get; set; }

        [JsonProperty("Video")]
        public List<string> Video { get; set; }
    }

    public partial class Memory
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Card slot")]
        public List<string> CardSlot { get; set; }

        [JsonProperty("Internal")]
        public List<string> Internal { get; set; }
    }

    public partial class Misc
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Colors")]
        public List<string> Colors { get; set; }

        [JsonProperty("Models")]
        public List<string> Models { get; set; }

        [JsonProperty("SAR")]
        public List<string> Sar { get; set; }

        [JsonProperty("SAR EU")]
        public List<string> SarEu { get; set; }

        [JsonProperty("Price")]
        public List<string> Price { get; set; }
    }

    public partial class Name
    {
        [JsonProperty("Main")]
        public List<string> Main { get; set; }

        [JsonProperty("Others")]
        public List<string> Others { get; set; }

    }

    public partial class Network
    {
        [JsonProperty("Technology")]
        public List<string> Technology { get; set; }

        [JsonProperty("2G bands")]
        public List<string> B2GBands { get; set; }

        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("3G bands")]
        public List<string> B3GBands { get; set; }

        [JsonProperty("4G bands")]
        public List<string> B4GBands { get; set; }

        [JsonProperty("Speed")]
        public List<string> Speed { get; set; }
    }

    public partial class Platform
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("OS")]
        public List<string> Os { get; set; }

        [JsonProperty("Chipset")]
        public List<string> Chipset { get; set; }

        [JsonProperty("CPU")]
        public List<string> Cpu { get; set; }

        [JsonProperty("GPU")]
        public List<string> Gpu { get; set; }
    }

    public partial class SelfieCamera
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Dual")]
        public List<string> Dual { get; set; }

        [JsonProperty("Features")]
        public List<string> Features { get; set; }

        [JsonProperty("Video")]
        public List<string> Video { get; set; }
    }

    public partial class Sound
    {
        [JsonProperty("Loudspeaker")]
        public List<string> Loudspeaker { get; set; }

        [JsonProperty("3.5mm jack")]
        public List<string> The35MmJack { get; set; }

        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }
    }

    public partial class Tests
    {
        [JsonProperty("Orphans")]
        public List<string> Orphans { get; set; }

        [JsonProperty("Performance")]
        public List<string> Performance { get; set; }

        [JsonProperty("Display")]
        public List<string> Display { get; set; }

        [JsonProperty("Loudspeaker")]
        public List<string> Loudspeaker { get; set; }

        [JsonProperty("Audio quality")]
        public List<string> AudioQuality { get; set; }
    }
}
