// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WebDataToJsonExtractor.Model.MobilePhone;
//
//    var gsmArenaModel = GsmArenaModel.FromJson(jsonString);

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Clerk.Processes.WebExtractorToJson.Model.GSMArena
{
    public class GsmArenaModel
    {
        [JsonProperty("Photo")]
        public Uri Photo { get; set; }

        [JsonProperty("Name")]
        public NameJson Name { get; set; }

        [JsonProperty("Network")]
        public NetworkJson Network { get; set; }

        [JsonProperty("Launch")]
        public LaunchJson Launch { get; set; }

        [JsonProperty("Body")]
        public BodyJson Body { get; set; }

        [JsonProperty("Display")]
        public DisplayJson Display { get; set; }

        [JsonProperty("Platform")]
        public PlatformJson Platform { get; set; }

        [JsonProperty("Memory")]
        public MemoryJson Memory { get; set; }

        [JsonProperty("Main Camera")]
        public MainCameraJson MainCamera { get; set; }

        [JsonProperty("Selfie camera")]
        public SelfieCameraJson SelfieCamera { get; set; }

        [JsonProperty("Sound")]
        public SoundJson Sound { get; set; }

        [JsonProperty("Comms")]
        public CommsJson Comms { get; set; }

        [JsonProperty("Features")]
        public FeaturesJson Features { get; set; }

        [JsonProperty("Battery")]
        public BatteryJson Battery { get; set; }

        [JsonProperty("Misc")]
        public MiscJson Misc { get; set; }

        [JsonProperty("Tests")]
        public TestsJson Tests { get; set; }
    }

    public class BatteryJson
    {
        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }

        [JsonProperty("Charging")]
        public string[] Charging { get; set; }
    }

    public class BodyJson
    {
        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }

        [JsonProperty("Dimensions")]
        public string[] Dimensions { get; set; }

        [JsonProperty("Weight")]
        public string[] Weight { get; set; }

        [JsonProperty("Build")]
        public string[] Build { get; set; }

        [JsonProperty("SIM")]
        public string[] Sim { get; set; }
    }

    public class CommsJson
    {
        [JsonProperty("WLAN")]
        public string[] Wlan { get; set; }

        [JsonProperty("Bluetooth")]
        public string[] Bluetooth { get; set; }

        [JsonProperty("GPS")]
        public string[] Gps { get; set; }

        [JsonProperty("NFC")]
        public string[] Nfc { get; set; }

        [JsonProperty("Radio")]
        public string[] Radio { get; set; }

        [JsonProperty("USB")]
        public string[] Usb { get; set; }
    }

    public class DisplayJson
    {
        [JsonProperty("Type")]
        public string[] Type { get; set; }

        [JsonProperty("Size")]
        public string[] Size { get; set; }

        [JsonProperty("Protection")]
        public string[] Protection { get; set; }

        [JsonProperty("Resolution")]
        public string[] Resolution { get; set; }

        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }
    }

    public class FeaturesJson
    {
        [JsonProperty("Sensors")]
        public string[] Sensors { get; set; }
    }

    public class LaunchJson
    {
        [JsonProperty("Announced")]
        public string[] Announced { get; set; }

        [JsonProperty("Status")]
        public string[] Status { get; set; }
    }

    public class MainCameraJson
    {
        public string[] Cameras { get; set; }

        [JsonProperty("Single")]
        private string[] SingleCamera { set => Cameras = value; }

        [JsonProperty("Dual")]
        private string[] DualCamera { set => Cameras = value; }

        [JsonProperty("Triple")]
        private string[] TripleCamera { set => Cameras = value; }

        [JsonProperty("Quad")]
        private string[] QuadCamera { set => Cameras = value; }

        [JsonProperty("Features")]
        public string[] Features { get; set; }

        [JsonProperty("Video")]
        public string[] Video { get; set; }
    }

    public class MemoryJson
    {
        [JsonProperty("Card slot")]
        public string[] CardSlot { get; set; }

        [JsonProperty("Internal")]
        public string[] Internal { get; set; }

        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }
    }

    public class MiscJson
    {
        [JsonProperty("Colors")]
        public string[] Colors { get; set; }

        [JsonProperty("Price")]
        public string[] Price { get; set; }
    }

    public class TestsJson
    {
        [JsonProperty("Performance")]
        public string[] Performance { get; set; }

        [JsonProperty("Display")]
        public string[] Display { get; set; }

        [JsonProperty("Loudspeaker")]
        public string[] Loudspeaker { get; set; }

        [JsonProperty("Audio quality")]
        public string[] AudioQuality { get; set; }
    }

    public class NameJson
    {
        [JsonProperty("Main")]
        public string[] Main { get; set; }
    }

    public class NetworkJson
    {
        public NetworkJson()
        {
            Bands = new Dictionary<string, string[]>();
        }


        [JsonProperty("Technology")]
        public string[] Technology { get; set; }

        public Dictionary<string, string[]> Bands { get; set; }

        [JsonProperty("2G bands")]
        private string[] The2GBands { set => Bands.Add("2G", value); }

        [JsonProperty("3G bands")]
        public string[] The3GBands { set => Bands.Add("3G", value); }

        [JsonProperty("4G bands")]
        public string[] The4GBands { set => Bands.Add("4G", value); }

        [JsonProperty("5G bands")]
        public string[] The5GBands { set => Bands.Add("5G", value); }

        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }

        [JsonProperty("Speed")]
        public string[] Speed { get; set; }
    }

    public class PlatformJson
    {
        [JsonProperty("OS")]
        public string[] Os { get; set; }

        [JsonProperty("Chipset")]
        public string[] Chipset { get; set; }

        [JsonProperty("CPU")]
        public string[] Cpu { get; set; }

        [JsonProperty("GPU")]
        public string[] Gpu { get; set; }
    }

    public class SelfieCameraJson
    {
        public string[] Cameras { get; set; }

        [JsonProperty("Single")]
        private string[] SingleCamera { set => Cameras = value; }

        [JsonProperty("Dual")]
        private string[] DualCamera { set => Cameras = value; }

        [JsonProperty("Triple")]
        private string[] TripleCamera { set => Cameras = value; }

        [JsonProperty("Quad")]
        private string[] QuadCamera { set => Cameras = value; }

        [JsonProperty("Features")]
        public string[] Features { get; set; }

        [JsonProperty("Video")]
        public string[] Video { get; set; }
    }

    public class SoundJson
    {
        [JsonProperty("Loudspeaker")]
        public string[] Loudspeaker { get; set; }

        [JsonProperty("3.5mm jack")]
        public string[] The35MmJack { get; set; }

        [JsonProperty("Orphans")]
        public string[] Orphans { get; set; }
    }
}
